export {
  EntitlementClient,
  createEntitlementClient,
  DEFAULT_TIMEOUT_MS,
  MAX_BODY_BYTES,
  type EntitlementClientOptions,
} from "./client.js";

export {
  EntitlementApiError,
  isAuthoritativeDenial,
  mapHttpError,
  parseRetryAfterMs,
  retryableForStatus,
  transportUnavailable,
  isStableErrorCode,
  STABLE_ERROR_CODES,
  stableErrorCodes,
  STABLE_ERROR_MESSAGES,
  STABLE_ERROR_STATUS,
  type StableEntitlementError,
  type StableErrorCode,
  type EntitlementClientDiagnostics,
} from "./errors.js";

export {
  OPENAPI_SHA256,
  REQUIRED_OPERATION_IDS,
  OPERATIONS,
  type PublicOperationId,
  type OperationMeta,
  type OperationRequestMap,
  type OperationResponseMap,
  type createActivationChallengeRequest,
  type createActivationChallengeResponse,
  type createActivationRequest,
  type createActivationResponse,
  type createDeactivationChallengeRequest,
  type createDeactivationChallengeResponse,
  type deleteCurrentActivationRequest,
  type deleteCurrentActivationResponse,
  type createLeaseChallengeRequest,
  type createLeaseChallengeResponse,
  type refreshLeaseRequest,
  type refreshLeaseResponse,
  type getWellKnownGrokdeskKeysResponse,
  type getReleaseManifestQuery,
  type getReleaseManifestResponse,
  type resolveReleaseRequest,
  type resolveReleaseResponse,
  type createDownloadGrantRequest,
  type createDownloadGrantResponse,
  type redeemDownloadQuery,
  type redeemDownloadResponse,
  type getHealthzResponse,
  type getReadyzResponse,
  type Error as EntitlementErrorBody,
  type ActivationChallengeRequest,
  type ActivationChallengeResponse,
  type ActivationRequest,
  type ActivationResponse,
  type PublicKeySet,
  type DownloadGrantResponse,
} from "./generated/api.js";
