#!/usr/bin/env python3
"""Real prop files for the Finder want-it beat."""
from pathlib import Path
d = Path("videos/assets/props/Marketing"); d.mkdir(parents=True, exist_ok=True)
(d / "brief.md").write_text("""# Competitor brief — desktop AI coworkers
_Generated by Grok Desk · 2026-07-11_

## Landscape
| Product | Platform | Model access | Desktop-native agency |
|---|---|---|---|
| Claude Cowork | macOS | Claude | Yes — tasks, folders |
| ChatGPT desktop | macOS/Win | GPT | Chat-first, limited tasks |
| Grok Desk | macOS/Win | SuperGrok (full surface) | Parallel tasks, schedules, memory |

## Takeaway
The open slot is subscription-native desktop agency for Grok users:
X search + Imagine + code execution driving real files on the user's machine.
""")
try:
    import openpyxl
except ImportError:
    raise SystemExit("pip3 install openpyxl first")
wb = openpyxl.Workbook(); ws = wb.active; ws.title = "Competitors"
rows = [["Product", "Platform", "Pricing", "Agent tasks", "Schedules"],
        ["Claude Cowork", "macOS", "$20/mo", "Yes", "No"],
        ["ChatGPT desktop", "macOS/Windows", "$20/mo", "Limited", "Yes"],
        ["Grok Desk", "macOS/Windows", "SuperGrok sub", "Parallel", "Cron + NL"]]
for r in rows: ws.append(r)
wb.save(d / "competitors.xlsx")
print("props written")
