/**
 * Write Grok CLI–native MCP configuration into a project-scoped
 * `.grok/config.toml` so headless `grok -p` actually spawns servers.
 *
 * Grok loads MCP from:
 *   - ~/.grok/config.toml (user)
 *   - <cwd>/.grok/config.toml and repo-root .grok/config.toml (project)
 *
 * Desk never invents env vars the CLI ignores; it writes real TOML.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { isPathInsideRoot } from "./paths.js";
import { isVaultRef, looksLikeSecretEnvKey } from "./secret-redact.js";

export interface McpServerForConfig {
  id: string;
  command: string;
  args: string[];
  env?: Record<string, string>;
  enabled: boolean;
}

/** Marker written inside every table Desk owns (for safe rewrite). */
export const MCP_MANAGED_MARKER = "# managed-by: grok-desk";

/** Escape a string for double-quoted TOML. */
export function tomlQuote(value: string): string {
  return (
    '"' +
    value
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/\t/g, "\\t") +
    '"'
  );
}

function tomlStringArray(values: string[]): string {
  return "[" + values.map((v) => tomlQuote(v)).join(", ") + "]";
}

function tomlInlineTable(map: Record<string, string>): string {
  const parts = Object.entries(map).map(
    ([k, v]) => `${sanitizeKey(k)} = ${tomlQuote(v)}`,
  );
  return "{ " + parts.join(", ") + " }";
}

/** MCP server names may only contain letters, numbers, hyphens, underscores. */
export function sanitizeMcpServerId(id: string): string {
  const cleaned = id.replace(/[^a-zA-Z0-9_-]/g, "-").replace(/^-+|-+$/g, "");
  return cleaned || "server";
}

function sanitizeKey(key: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) return key;
  return tomlQuote(key);
}

/**
 * Render only the [mcp_servers.*] sections Desk owns.
 * Other config sections are not written here (skills paths etc. go elsewhere).
 * Each table starts with a managed-by marker so rewrites can identify Desk rows.
 */
export function renderMcpServersToml(servers: McpServerForConfig[]): string {
  const enabled = servers.filter((s) => s.enabled);
  if (enabled.length === 0) {
    return "# Grok Desk: no MCP servers enabled\n";
  }
  const lines: string[] = [
    "# Generated by Grok Desk — project-scoped MCP for this workspace",
    "# Do not put secrets here if this folder is shared; use ${ENV} placeholders.",
    "",
  ];
  for (const s of enabled) {
    const name = sanitizeMcpServerId(s.id);
    lines.push(`[mcp_servers.${name}]`);
    lines.push(MCP_MANAGED_MARKER);
    lines.push(`command = ${tomlQuote(s.command)}`);
    lines.push(`args = ${tomlStringArray(s.args)}`);
    if (s.env && Object.keys(s.env).length > 0) {
      lines.push(`env = ${tomlInlineTable(s.env)}`);
    }
    lines.push(`enabled = true`);
    lines.push("");
  }
  return lines.join("\n");
}

/**
 * Expand ${VAR} / $HOME in args and env at spawn time.
 * Unresolved non-HOME/USER placeholders are left as-is (CLI may expand later).
 */
export function expandMcpPlaceholders(
  servers: McpServerForConfig[],
  env: NodeJS.ProcessEnv = process.env,
): McpServerForConfig[] {
  return servers.map((s) => ({
    ...s,
    args: s.args.map((a) => expandOne(a, env)),
    env: s.env
      ? Object.fromEntries(
          Object.entries(s.env).map(([k, v]) => [k, expandOne(v, env)]),
        )
      : undefined,
  }));
}

function expandOne(
  value: string,
  env: NodeJS.ProcessEnv,
  opts?: { expandSecrets?: boolean; envKey?: string },
): string {
  const home = env.HOME || env.USERPROFILE || "/tmp";
  const user = env.USER || env.USERNAME || "user";
  let out = value
    .replaceAll("${HOME}", home)
    .replaceAll("$HOME", home)
    .replaceAll("${USER}", user);
  // Never expand vault refs or secret-looking env keys into project files.
  if (isVaultRef(value)) return value;
  if (opts?.expandSecrets === false && opts.envKey && looksLikeSecretEnvKey(opts.envKey)) {
    return value;
  }
  out = out.replace(/\$\{([A-Z0-9_]+)\}/g, (match, name: string) => {
    if (name === "HOME" || name === "USER") return match;
    // Keep secret env placeholders unexpanded in project-scoped config.
    if (opts?.expandSecrets === false && looksLikeSecretEnvKey(name)) {
      return match;
    }
    const v = env[name];
    return v != null && v !== "" ? v : match;
  });
  return out;
}

/**
 * Expand placeholders for project-scoped config: HOME/USER only for paths;
 * secret-like env keys stay as ${VAR} so literals never land in the workspace.
 */
export function expandMcpPlaceholdersSafeForProject(
  servers: McpServerForConfig[],
  env: NodeJS.ProcessEnv = process.env,
): McpServerForConfig[] {
  return servers.map((s) => ({
    ...s,
    args: s.args.map((a) => expandOne(a, env, { expandSecrets: false })),
    env: s.env
      ? Object.fromEntries(
          Object.entries(s.env).map(([k, v]) => [
            k,
            expandOne(v, env, { expandSecrets: false, envKey: k }),
          ]),
        )
      : undefined,
  }));
}

function ensureGrokGitignore(grokDir: string): void {
  const gi = path.join(grokDir, ".gitignore");
  if (!fs.existsSync(gi)) {
    fs.writeFileSync(gi, "config.toml\nskills/\n", "utf8");
  }
}

/**
 * Write project MCP config under `primaryCwd/.grok/config.toml`.
 * Replaces only Desk-managed tables (by managedIds or managed-by marker).
 * Pass ALL Desk-known servers (enabled + disabled) so disabling strips stale tables.
 * Returns the path written, or null if nothing to write and no prior file.
 */
export function writeProjectMcpConfig(
  primaryCwd: string,
  servers: McpServerForConfig[],
  env: NodeJS.ProcessEnv = process.env,
): string | null {
  const enabled = servers.filter((s) => s.enabled);
  const managedIds = new Set(
    servers.map((s) => sanitizeMcpServerId(s.id)),
  );
  const grokDir = path.join(primaryCwd, ".grok");
  const configPath = path.join(grokDir, "config.toml");

  if (enabled.length === 0 && managedIds.size === 0) {
    return fs.existsSync(configPath) ? configPath : null;
  }

  if (enabled.length === 0 && !fs.existsSync(configPath)) {
    // Nothing enabled and no prior file — don't create an empty config.
    return null;
  }

  fs.mkdirSync(grokDir, { recursive: true });
  ensureGrokGitignore(grokDir);

  // SEC-02: never expand secret env values into the user project tree.
  const expanded = expandMcpPlaceholdersSafeForProject(enabled, env);
  const body = renderMcpServersToml(expanded);

  let existing = "";
  if (fs.existsSync(configPath)) {
    try {
      existing = fs.readFileSync(configPath, "utf8");
    } catch {
      existing = "";
    }
  }
  const preserved = stripMcpServerSections(existing, managedIds);
  const next =
    (preserved.trim() ? preserved.trimEnd() + "\n\n" : "") + body;
  fs.writeFileSync(configPath, next, "utf8");
  return configPath;
}

/**
 * Remove Desk-managed [mcp_servers.*] tables so we can rewrite them cleanly.
 * Keeps user-authored tables (no marker, not in managedIds).
 * Does NOT strip [mcp.*] or other unrelated sections.
 */
export function stripMcpServerSections(
  toml: string,
  managedIds: Set<string> = new Set(),
): string {
  if (!toml.trim()) return "";
  const lines = toml.split(/\r?\n/);
  const out: string[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i]!;
    // Drop our generator comments when rewriting
    if (line.startsWith("# Generated by Grok Desk")) {
      i++;
      continue;
    }
    if (line.startsWith("# Do not put secrets here if this folder is shared")) {
      i++;
      continue;
    }
    if (line.startsWith("# Grok Desk: no MCP servers enabled")) {
      i++;
      continue;
    }

    const header = line.match(/^\s*\[([^\]]+)\]\s*$/);
    if (header) {
      const name = header[1]!.trim();
      if (name === "mcp_servers" || name.startsWith("mcp_servers.")) {
        const serverName =
          name === "mcp_servers" ? "" : name.slice("mcp_servers.".length);
        const tableLines = [line];
        i++;
        while (i < lines.length) {
          const next = lines[i]!;
          if (/^\s*\[[^\]]+\]\s*$/.test(next)) break;
          tableLines.push(next);
          i++;
        }
        const bodyText = tableLines.slice(1).join("\n");
        const isManaged =
          (serverName !== "" && managedIds.has(serverName)) ||
          bodyText.includes("managed-by: grok-desk");
        if (isManaged) {
          continue;
        }
        out.push(...tableLines);
        continue;
      }
    }
    out.push(line);
    i++;
  }
  while (out.length && out[out.length - 1]!.trim() === "") out.pop();
  return out.join("\n");
}

/**
 * Full recursive copy of a skill pack directory (SKILL.md + resources).
 * Used when symlink is unavailable (Windows / permission).
 */
export function copySkillDir(src: string, dest: string): void {
  fs.cpSync(src, dest, { recursive: true });
}

/**
 * Install skill pack directories into `destRoot/<name>` (symlink or copy).
 * Shared by project scope (`.grok/skills`) and isolated GROK_HOME (`skills`).
 */
export function installSkillPacks(
  destRoot: string,
  skillRoots: string[],
): string[] {
  const installed: string[] = [];
  fs.mkdirSync(destRoot, { recursive: true });

  for (const root of skillRoots) {
    if (!root || !fs.existsSync(root)) continue;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(root, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const ent of entries) {
      if (!ent.isDirectory()) continue;
      // Skip path-segment names that would escape destRoot under path.join.
      if (!ent.name || ent.name === "." || ent.name === ".." || ent.name.includes("/") || ent.name.includes("\\")) {
        continue;
      }
      const src = path.join(root, ent.name);
      const skillMd = path.join(src, "SKILL.md");
      if (!fs.existsSync(skillMd)) continue;
      const dest = path.join(destRoot, ent.name);
      const resolvedDest = path.resolve(dest);
      const resolvedRoot = path.resolve(destRoot);
      // Case-aware on Windows; refuse escape from destRoot.
      if (!isPathInsideRoot(resolvedDest, resolvedRoot)) {
        continue;
      }
      try {
        if (fs.existsSync(dest)) {
          const st = fs.lstatSync(dest);
          if (st.isSymbolicLink() || st.isDirectory()) {
            installed.push(dest);
            continue;
          }
        }
        try {
          fs.symlinkSync(src, dest, "dir");
        } catch {
          // Windows / permission fallback: full recursive copy
          copySkillDir(src, dest);
        }
        installed.push(dest);
      } catch {
        // ignore individual pack failures
      }
    }
  }
  return installed;
}

/**
 * Install skill pack directories into `<cwd>/.grok/skills/<name>` so the
 * Grok CLI discovers them (project scope). Prefers symlinks; falls back to copy.
 */
export function installSkillsIntoProject(
  primaryCwd: string,
  skillRoots: string[],
): string[] {
  return installSkillPacks(path.join(primaryCwd, ".grok", "skills"), skillRoots);
}

/**
 * Install skill packs into an isolated GROK_HOME (`$GROK_HOME/skills`).
 * Always used for Desk-owned packs so image/marketing skills work even when
 * the project folder is not trusted (project install is still gated separately).
 */
export function installSkillsIntoGrokHome(
  grokHome: string,
  skillRoots: string[],
): string[] {
  return installSkillPacks(path.join(grokHome, "skills"), skillRoots);
}

/** Redact likely secrets from strings shown to the model. */
export function redactSecretsForPrompt(text: string): string {
  return text
    .replace(
      /(postgres(?:ql)?:\/\/)([^:\s]+):([^@\s]+)@/gi,
      "$1$2:***@",
    )
    .replace(
      /\b(ghp_|gho_|github_pat_|sk-|xox[baprs]-|AKIA)[A-Za-z0-9_\-/+=]{8,}/g,
      "[redacted]",
    )
    .replace(
      /([A-Z0-9_]*(?:TOKEN|SECRET|PASSWORD|API_KEY|ACCESS_KEY)[A-Z0-9_]*)\s*=\s*["']?([^\s"']+)/gi,
      "$1=[redacted]",
    );
}


/**
 * Write MCP config to a private ephemeral directory (0600) for provider runs.
 * Prefer this over project .grok/config.toml when secrets must be expanded.
 * Caller must delete the directory after the run.
 */
export function writeEphemeralMcpConfig(
  servers: McpServerForConfig[],
  env: NodeJS.ProcessEnv = process.env,
  baseDir?: string,
): { dir: string; configPath: string } | null {
  const enabled = servers.filter((s) => s.enabled);
  if (enabled.length === 0) return null;
  const dir =
    baseDir ??
    fs.mkdtempSync(path.join(os.tmpdir(), "grokdesk-mcp-"));
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  const expanded = expandMcpPlaceholders(enabled, env);
  const body = renderMcpServersToml(expanded);
  const configPath = path.join(dir, "config.toml");
  fs.writeFileSync(configPath, body, { encoding: "utf8", mode: 0o600 });
  try {
    fs.chmodSync(dir, 0o700);
    fs.chmodSync(configPath, 0o600);
  } catch {
    /* best-effort on platforms without chmod */
  }
  return { dir, configPath };
}
